### ISSUE TITLE
Release plan AmpForm v0.12

### ISSUE THREAD

**Issue by redeboer** [ComPWA/ampform#182]
- [x] #174
- [x] #172
- [x] Create pre-release --> [v0.12.0a0](https://github.com/ComPWA/ampform/releases/tag/0.12.0a0) 
- [x] Adapt and test TensorWaves interface
  https://github.com/ComPWA/tensorwaves/pull/345
- [x] Compare performance computation kinematic variables
  https://github.com/ComPWA/ampform/pull/177#pullrequestreview-805513472
  --> https://github.com/ComPWA/tensorwaves/pull/345#issuecomment-986707089
- ~Rewrite `ArrayMultiplication` and `ArrayAxisSum` in terms of existing SymPy classes~
  https://github.com/ComPWA/ampform/pull/177#discussion_r749307147
  --> AmpForm v0.12.1
