### ISSUE TITLE
Adapt implementation to QRules v0.10

### ISSUE THREAD

**Issue by redeboer** [ComPWA/ampform#347]
See also #281 
```[tasklist]
### Tasks
- [x] Write workflow for testing AmpForm with QRules v0.9
- [x] Write functionality to determine QRules version
- [ ] https://github.com/ComPWA/qrules/pull/249
- [x] Release [QRules v0.10.1](https://github.com/ComPWA/qrules/releases/tag/0.10.1)
- [x] Adapt AmpForm implementation to QRules v0.10 with backward compatibility
```
