### ISSUE TITLE
Implement extra rotation for spin alignment of different sub-systems

### ISSUE THREAD

**Issue by redeboer** [ComPWA/ampform#6]
When dealing with different Subsystems in the same amplitude description, an extra rotation has to be introduced in order to align one system to another. Otherwise the `phi` angular distributions can be incorrect.

Different Subsystems means that intermediate states appear in different groups of final state particles.

### Literature
- Mikhashenko _et al._, “Dalitz-Plot Decomposition for Three-Body Decays”, 2020, [10.1103/PhysRevD.101.034033](https://journals.aps.org/prd/abstract/10.1103/PhysRevD.101.034033)
- Marangotto, “Helicity Amplitudes for Generic Multi-Body Particle Decays Featuring Multiple Decay Chains”, 2020, [10.1155/2020/6674595](https://doi.org/10.1155/2020/6674595).
- Chilikin _et al._, “Experimental Constraints on the Spin and Parity of the Z(4430)+”, 2013, [10.1103/PhysRevD.88.074026](https://journals.aps.org/prd/abstract/10.1103/PhysRevD.88.074026). See Appendix A.
- Wang _et al._, “A Novel Method to Test Particle Ordering and Final State Alignment in Helicity Formalism”, 2020, [arXiv: 2012.03699](https://arxiv.org/pdf/2012.03699).
- Kutschke, “An Angular Distribution Cookbook”, 1996 [[here]](https://home.fnal.gov/~kutschke/Angdist/angdist.ps)
- Richman, “An Experimenter’s Guide to the Helicity Formalism”, 1984 [[here]](https://inspirehep.net/literature/202987)

### To-do list
- [x] Generate Wigner-_D_ chain in Marangotto Eq.(45)
  #213
- [x] Sum over product of all combinations in Eq.(45)
- [ ] Skip _m_ = 0 in case of massless particles
- [x] Rewrite sum combinations with [`sympy.Sum`](https://docs.sympy.org/latest/modules/concrete.html#sympy.concrete.summations.Sum) and a (unique!) [`Dummy`](https://docs.sympy.org/latest/modules/core.html#sympy.core.symbol.Dummy) index.
- [x] Compute Wigner rotation angles _α_, _β_, _γ_
  #9
- [ ] Check if same procedure applies for `formalism="canonical-helicity"`
- [x] #10
- [ ] Test if distributions are the same if a different reference `Topology` is chosen.
- [ ] ~#8~
